name: Build Rootless Tweak

on:
  workflow_dispatch:

env:
  SWIFTPROTOBUF_VERSION: "1.29.0"

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: ${{ github.workspace }}/theos
      THEOS_PACKAGE_SCHEME: rootless

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      # Cache Theos
      - name: Cache Theos
        uses: actions/cache@v4
        id: cache-theos
        with:
          path: theos
          key: theos-cache-v1

      - name: Setup Theos (if cache miss)
        if: steps.cache-theos.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      # Install deps
      - name: Install Dependencies
        run: |
          brew install make dpkg ldid wget
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      # Cache SwiftProtobuf (rootless only)
      - name: Cache SwiftProtobuf
        uses: actions/cache@v4
        id: cache-swiftprotobuf
        with:
          path: theos/lib/iphone/rootless/SwiftProtobuf.framework
          key: swiftprotobuf-rootless-${{ env.SWIFTPROTOBUF_VERSION }}

      - name: Install SwiftProtobuf (if cache miss)
        if: steps.cache-swiftprotobuf.outputs.cache-hit != 'true'
        run: |
          mkdir swiftprotobuf && cd swiftprotobuf
          wget https://github.com/whoeevee/swift-protobuf/releases/download/${{ env.SWIFTPROTOBUF_VERSION }}/org.swift.protobuf.swiftprotobuf_${{ env.SWIFTPROTOBUF_VERSION }}_iphoneos-arm64.deb
          ar -x org.swift.protobuf.swiftprotobuf_${{ env.SWIFTPROTOBUF_VERSION }}_iphoneos-arm64.deb
          tar -xvf data.tar.lzma
          cp -r var/jb/Library/Frameworks/SwiftProtobuf.framework $THEOS/lib/iphone/rootless

      # Build
      - name: Build Rootless Package
        run: make package FINALPACKAGE=1

      # Upload
      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: rootless-deb
          path: packages/*.deb
          if-no-files-found: error
